name: Check documentation build

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum-graphcore'
          path: optimum-graphcore

      - name: Make documentation
        run: |
          cd optimum-graphcore
          git fetch origin
          git checkout documentation
          make doc BUILD_DIR=graphcore-doc-build
          sudo rm -rf graphcore-doc-build